# Generated by Django 5.2.15 on 2026-08-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idp_subject',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='IdP subject'),
        ),
    ]
