# Generated by Django 5.2.15 on 2026-08-17 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_provision_designated_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialEpoch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True, verbose_name='JWT ID')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='first seen at')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='expires at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_epochs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
