"""In-test signing material and the two stubs the Bearer suites share.

NFR-7 is why nothing here is a committed key: every keypair is generated by the
test that asks for it and lives only as long as the session does. 2048 bits and a
session- or module-scoped fixture keep the cost off the per-test path.

The stubs are here rather than duplicated in two suites because they are the
seams AC #5 depends on. `StubFetch` is what a `JWKSKeyStore` is constructed
around so that no test in this repository opens a socket, and `FakeClock` is what
lets a sixty-second rate-limit window be crossed without a test sleeping through
it.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import TYPE_CHECKING
from typing import Any
from typing import Final

import jwt
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.asymmetric import rsa
from jwt.algorithms import RSAAlgorithm

if TYPE_CHECKING:
    from collections.abc import Mapping

__all__ = [
    "FakeClock",
    "SigningKey",
    "StubFetch",
    "generate",
    "jwks_document",
    "sign_with_a_symmetric_key",
    "sign_with_an_elliptic_curve_key",
]

#: The smallest modulus a real IdP would publish. Small enough that a
#: session-scoped generation does not show up in the suite's runtime, large
#: enough that the token being verified is the shape production verifies.
KEY_SIZE: Final = 2048
PUBLIC_EXPONENT: Final = 65537

#: The one asymmetric algorithm the component's default allowlist admits.
SIGNING_ALGORITHM: Final = "RS256"

#: A symmetric algorithm, which the allowlist does *not* admit. Signing with it
#: is how the algorithm-confusion probe is expressed.
SYMMETRIC_ALGORITHM: Final = "HS256"

#: A second *asymmetric* family. `RS256,ES256` is a supported value of
#: `COMPONENT_OIDC_ALGORITHMS`, so an allowlist admitting both while the IdP
#: publishes only RSA keys is a shipped configuration -- and a token signed with
#: this algorithm under a published RSA `kid` is what proves the key/algorithm
#: mismatch is refused rather than raised.
ELLIPTIC_CURVE_ALGORITHM: Final = "ES256"

#: Material for that probe. Not a credential of any kind -- no component ever
#: accepts an HS256 token, which is the whole point of the case it serves.
_SYMMETRIC_MATERIAL: Final = "material no deployment would ever hold"


@dataclass(frozen=True)
class SigningKey:
    """One RSA keypair with the `kid` an IdP would publish it under.

    Attributes:
        kid: The key identifier. Tokens carry it in their header and the key
            store indexes on it.
        private_key: The private half, which never leaves the test process.

    """

    kid: str
    private_key: rsa.RSAPrivateKey

    def public_jwk(self) -> dict[str, Any]:
        """Render the public half as the JWK an IdP would publish.

        Returns:
            The JWK with `kid`, `alg` and `use` filled in. Only the public half
            is rendered -- a JWK Set carrying private material would be a test
            that proves the store works against something no IdP serves.

        """
        rendered: dict[str, Any] = json.loads(RSAAlgorithm.to_jwk(self.private_key.public_key()))
        return {**rendered, "kid": self.kid, "alg": SIGNING_ALGORITHM, "use": "sig"}

    def sign(self, claims: Mapping[str, Any], *, kid: str | None = None) -> str:
        """Sign a set of claims as this key.

        Args:
            claims: The claims to mint into a token.
            kid: The identifier to advertise in the header, when it must differ
                from this key's own -- an unpublished `kid`, or the published one
                over another key's signature.

        Returns:
            The encoded token.

        """
        return jwt.encode(
            dict(claims),
            self.private_key,
            algorithm=SIGNING_ALGORITHM,
            headers={"kid": kid if kid is not None else self.kid},
        )


def generate(kid: str) -> SigningKey:
    """Generate one keypair.

    Args:
        kid: The identifier to publish it under.

    Returns:
        The keypair. Call this from a session- or module-scoped fixture: RSA
        generation is the slowest thing in either suite.

    """
    return SigningKey(kid=kid, private_key=rsa.generate_private_key(public_exponent=PUBLIC_EXPONENT, key_size=KEY_SIZE))


def jwks_document(*keys: SigningKey) -> dict[str, Any]:
    """Build the JWK Set document an IdP would serve for these keys.

    Args:
        *keys: The keys to publish, in order.

    Returns:
        The document, shaped as RFC 7517 defines it.

    """
    return {"keys": [key.public_jwk() for key in keys]}


def sign_with_a_symmetric_key(claims: Mapping[str, Any], *, kid: str) -> str:
    """Mint a token signed with HS256, which the allowlist must refuse.

    Args:
        claims: The claims to mint.
        kid: The identifier to advertise, ordinarily a published one -- the point
            of the case is that a token naming a real key and signed by another
            algorithm is still refused.

    Returns:
        The encoded token.

    """
    return jwt.encode(dict(claims), _SYMMETRIC_MATERIAL, algorithm=SYMMETRIC_ALGORITHM, headers={"kid": kid})


def sign_with_an_elliptic_curve_key(claims: Mapping[str, Any], *, kid: str) -> str:
    """Mint an ES256 token under a `kid` the IdP published an *RSA* key for.

    The published key and the token's algorithm are then two different families,
    which is what PyJWT's key preparation refuses -- with a bare `TypeError` that
    is not under `InvalidTokenError` and therefore escapes a naive catch as a 500
    rather than a 401.

    Args:
        claims: The claims to mint.
        kid: The identifier to advertise, ordinarily a published one.

    Returns:
        The encoded token.

    """
    key = ec.generate_private_key(ec.SECP256R1())
    return jwt.encode(dict(claims), key, algorithm=ELLIPTIC_CURVE_ALGORITHM, headers={"kid": kid})


class FakeClock:
    """A monotonic clock a test advances by hand.

    The TTL and the rate limit are both measured in minutes and hours, so a test
    that waited for either would not be a unit test. `JWKSKeyStore` takes its
    clock as a constructor argument for exactly this.
    """

    def __init__(self, start: float = 1_000.0) -> None:
        """Start the clock somewhere that is not zero.

        Args:
            start: The initial reading. Non-zero by default so a test cannot
                accidentally pass because a window happens to be satisfied by an
                origin at zero.

        """
        self.now = start

    def __call__(self) -> float:
        """Read the clock.

        Returns:
            The current reading.

        """
        return self.now

    def advance(self, seconds: float) -> None:
        """Move the clock forward.

        Args:
            seconds: How far.

        """
        self.now += seconds


class StubFetch:
    """A JWKS fetch that counts its calls and never opens a socket.

    Attributes:
        document: What the next call returns. A test rotates keys by replacing
            it.
        calls: How many times it has been called, which is the assertion almost
            every case in the AC #5 suite makes.
        failure: An exception to raise instead of answering, for the cases that
            prove a failed fetch leaves the cache intact.

    """

    def __init__(self, document: dict[str, Any]) -> None:
        """Start with a document and no failures.

        Args:
            document: The JWK Set to answer with.

        """
        self.document = document
        self.calls = 0
        self.failure: Exception | None = None

    def __call__(self) -> dict[str, Any]:
        """Answer one fetch.

        Returns:
            The current document.

        Raises:
            Exception: Whatever `failure` holds, when it holds anything.

        """
        self.calls += 1
        if self.failure is not None:
            raise self.failure
        return self.document
